server:  
  port: ${PORT:5000}
  servlet:
    contextPath: /api
  
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_city}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    
    

